FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 5000

FROM base AS final

# add globalization support
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

COPY ["ems/publish", "."]
COPY neptuneserver/NT.pfx /app/NT.pfx
COPY Jits.Neptune.Web.Framework.xml /app/Jits.Neptune.Web.Framework.xml
COPY ems/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

WORKDIR /app
RUN mkdir bin
WORKDIR /app

RUN mkdir App_Data
COPY ems/settings_SqlServer186.json /app/App_Data/appsettings.json
# COPY ems/SimpleList.mrt /app/App_Data/SimpleList.mrt

ENTRYPOINT "/entrypoint.sh"
