FROM aspnet7 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 5000

FROM base AS final

# add globalization support
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

COPY ["payment/publish", "."]
COPY neptuneserver/NT.pfx /app/NT.pfx
COPY Jits.Neptune.Web.Framework.xml /app/Jits.Neptune.Web.Framework.xml
COPY payment/migration-data/ /app/

COPY payment/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

WORKDIR /app
RUN mkdir bin
WORKDIR /app

#RUN mkdir App_Data
#COPY payment/settings_SqlServer.json /app/App_Data/appsettings.json
COPY payment/migration-data/CodeListData.json /app/

ENTRYPOINT "/entrypoint.sh"
