version: '3.4'

services:
  neptunedb_mariadb:
    image: mariadb
    container_name: neptunedb_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql_data:/var/lib/mysql:Z
    # command:
    #   - "mysqld"
    #   - "--slave_domain_parallel_threads=1000" #Max: 16383
    #   - "--slave_parallel_threads=1000" #Max: 16383
    #   - "--binlog_expire_logs_seconds=259200" #Default: 864000

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15672:15672"
    volumes:
      - /home/rabbitmq_data:/var/lib/rabbitmq/mnesia

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - neptunedb_mariadb
    environment:
      - PMA_HOST=neptunedb_mariadb
      - PMA_PORT=3306
    restart: always
    ports:
      - "8886:80"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "8040:8000"
      - "9040:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  neptuneserver:
    image: ${DOCKER_REGISTRY-}neptuneserver
    build:
      context: .
      dockerfile: neptuneserver/Dockerfile_deploy
    container_name: neptuneserver
    environment:
      - NEPTUNE_DB_ONLINE_SERVER_NAME=neptunedb_mariadb
      - NEPTUNE_DB_ONLINE_SERVER_PORT=3306
      - NEPTUNE_DB_ONLINE_NAME=neptune
      - NEPTUNE_DB_ONLINE_SCHEMA=neptune
      - NEPTUNE_DB_ONLINE_RDBMS_TYPE=MariaDB
      - NEPTUNE_DB_ONLINE_USERNAME=neptune
      - NEPTUNE_DB_ONLINE_PASSWORD=bmVwdHVuZQ==
    depends_on:
      - neptunedb_mariadb
      - rabbitmq
    restart: always
    ports:
      - "105:105"
      - "109:109"

  accounting.api:
    image: ${DOCKER_REGISTRY-}accountingapi
    build:
      context: .
      dockerfile: accounting/Dockerfile
    container_name: accounting.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8050:80"
      - "5050:5000"

  admin.api:
    image: ${DOCKER_REGISTRY-}adminapi
    build:
      context: .
      dockerfile: admin/Dockerfile
    container_name: admin.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8051:80"
      - "5051:5000"

  cash.api:
    image: ${DOCKER_REGISTRY-}cashapi
    build:
      context: .
      dockerfile: cash/Dockerfile
    container_name: cash.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8052:80"
      - "5052:5000"

  credit.api:
    image: ${DOCKER_REGISTRY-}creditapi
    build:
      context: .
      dockerfile: credit/Dockerfile
    container_name: credit.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8053:80"
      - "5053:5000"

  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: customer/Dockerfile
    container_name: customer.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8054:80"
      - "5054:5000"

  deposit.api:
    image: ${DOCKER_REGISTRY-}depositgapi
    build:
      context: .
      dockerfile: deposit/Dockerfile
    container_name: deposit.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8055:80"
      - "5055:5000"

  fixedasset.api:
    image: ${DOCKER_REGISTRY-}fixedassetapi
    build:
      context: .
      dockerfile: fixedasset/Dockerfile
    container_name: fixedasset.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8056:80"
      - "5056:5000"

  fx.api:
    image: ${DOCKER_REGISTRY-}fxapi
    build:
      context: .
      dockerfile: fx/Dockerfile
    container_name: fx.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8057:80"
      - "5057:5000"

  ifc.api:
    image: ${DOCKER_REGISTRY-}ifcapi
    build:
      context: .
      dockerfile: ifc/Dockerfile
    container_name: ifc.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8058:80"
      - "5058:5000"

  mortgage.api:
    image: ${DOCKER_REGISTRY-}mortgageapi
    build:
      context: .
      dockerfile: mortgage/Dockerfile
    container_name: mortgage.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8059:80"
      - "5059:5000"

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: payment/Dockerfile
    container_name: payment.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8060:80"
      - "5060:5000"

  batch.api:
    image: ${DOCKER_REGISTRY-}batchapi
    build:
      context: .
      dockerfile: batch/Dockerfile
    container_name: batch.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8061:80"
      - "5061:5000"

  cms.api:
    image: ${DOCKER_REGISTRY-}cmsapi
    build:
      context: .
      dockerfile: cms/Dockerfile
    container_name: cms.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8066:80"
      - "5066:5000"

  cms1.api:
    image: ${DOCKER_REGISTRY-}cmsapi
    build:
      context: .
      dockerfile: cms/Dockerfile
    container_name: cms1.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8166:80"
      - "5166:5000"

  cms2.api:
    image: ${DOCKER_REGISTRY-}cmsapi
    build:
      context: .
      dockerfile: cms/Dockerfile
    container_name: cms2.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8266:80"
      - "5266:5000"

  nginx:
    image: ${DOCKER_REGISTRY-}nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  voucher.api:
    image: ${DOCKER_REGISTRY-}voucherapi
    build:
      context: .
      dockerfile: voucher/Dockerfile
    container_name: voucher.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8063:80"
      - "5063:5000"

  report.api:
    image: ${DOCKER_REGISTRY-}reportapi
    build:
      context: .
      dockerfile: report/Dockerfile
    container_name: report.api
    depends_on:
      - neptunedb_mariadb
      - neptuneserver
    ports:
      - "8067:443"
      - "5067:5000"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  portainer_data:
