FROM aspnet7 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 5000

FROM base AS final

# add globalization support
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

COPY ["email/publish", "."]
COPY neptuneserver/NT.pfx /app/NT.pfx
COPY Jits.Neptune.Web.Framework.xml /app/Jits.Neptune.Web.Framework.xml
COPY email/entrypoint.sh /entrypoint.sh
COPY email/migration-data/ /app/

RUN chmod 755 /entrypoint.sh

WORKDIR /app
RUN mkdir bin
WORKDIR /app

#RUN mkdir App_Data
#COPY email/settings_SqlServer.json /app/App_Data/appsettings.json

ENTRYPOINT "/entrypoint.sh"
