CREATE USER 'neptune'@'%' IDENTIFIED BY 'neptune';
GRANT ALL PRIVILEGES ON *.* TO 'neptune'@'%' WITH GRANT OPTION;
ALTER USER 'neptune'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `neptune`;
GRANT ALL PRIVILEGES ON `neptune`.* TO 'neptune'@'%';
GRANT ALL PRIVILEGES ON `neptune\_%`.* TO 'neptune'@'%';

CREATE USER 'neptune_archive'@'%' IDENTIFIED BY 'neptune_archive';
GRANT ALL PRIVILEGES ON *.* TO 'neptune_archive'@'%' WITH GRANT OPTION;
ALTER USER 'neptune_archive'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `neptune_archive`;
GRANT ALL PRIVILEGES ON `neptune_archive`.* TO 'neptune_archive'@'%';
GRANT ALL PRIVILEGES ON `neptune_archive\_%`.* TO 'neptune_archive'@'%';

CREATE USER 'o9admin'@'%' IDENTIFIED BY 'o9admin';
GRANT ALL PRIVILEGES ON *.* TO 'o9admin'@'%' WITH GRANT OPTION;
ALTER USER 'o9admin'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9admin`;
GRANT ALL PRIVILEGES ON `o9admin`.* TO 'o9admin'@'%';
GRANT ALL PRIVILEGES ON `o9admin\_%`.* TO 'o9admin'@'%';

CREATE USER 'o9accounting'@'%' IDENTIFIED BY 'o9accounting';
GRANT ALL PRIVILEGES ON *.* TO 'o9accounting'@'%' WITH GRANT OPTION;
ALTER USER 'o9accounting'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9accounting`;
GRANT ALL PRIVILEGES ON `o9accounting`.* TO 'o9accounting'@'%';
GRANT ALL PRIVILEGES ON `o9accounting\_%`.* TO 'o9accounting'@'%';

CREATE USER 'o9cash'@'%' IDENTIFIED BY 'o9cash';
GRANT ALL PRIVILEGES ON *.* TO 'o9cash'@'%' WITH GRANT OPTION;
ALTER USER 'o9cash'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9cash`;
GRANT ALL PRIVILEGES ON `o9cash`.* TO 'o9cash'@'%';
GRANT ALL PRIVILEGES ON `o9cash\_%`.* TO 'o9cash'@'%';

CREATE USER 'o9fx'@'%' IDENTIFIED BY 'o9fx';
GRANT ALL PRIVILEGES ON *.* TO 'o9fx'@'%' WITH GRANT OPTION;
ALTER USER 'o9fx'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9fx`;
GRANT ALL PRIVILEGES ON `o9fx`.* TO 'o9fx'@'%';
GRANT ALL PRIVILEGES ON `o9fx\_%`.* TO 'o9fx'@'%';

CREATE USER 'o9customer'@'%' IDENTIFIED BY 'o9customer';
GRANT ALL PRIVILEGES ON *.* TO 'o9customer'@'%' WITH GRANT OPTION;
ALTER USER 'o9customer'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9customer`;
GRANT ALL PRIVILEGES ON `o9customer`.* TO 'o9customer'@'%';
GRANT ALL PRIVILEGES ON `o9customer\_%`.* TO 'o9customer'@'%';

CREATE USER 'o9ifc'@'%' IDENTIFIED BY 'o9ifc';
GRANT ALL PRIVILEGES ON *.* TO 'o9ifc'@'%' WITH GRANT OPTION;
ALTER USER 'o9ifc'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9ifc`;
GRANT ALL PRIVILEGES ON `o9ifc`.* TO 'o9ifc'@'%';
GRANT ALL PRIVILEGES ON `o9ifc\_%`.* TO 'o9ifc'@'%';

CREATE USER 'o9credit'@'%' IDENTIFIED BY 'o9credit';
GRANT ALL PRIVILEGES ON *.* TO 'o9credit'@'%' WITH GRANT OPTION;
ALTER USER 'o9credit'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9credit`;
GRANT ALL PRIVILEGES ON `o9credit`.* TO 'o9credit'@'%';
GRANT ALL PRIVILEGES ON `o9credit\_%`.* TO 'o9credit'@'%';

CREATE USER 'o9deposit'@'%' IDENTIFIED BY 'o9deposit';
GRANT ALL PRIVILEGES ON *.* TO 'o9deposit'@'%' WITH GRANT OPTION;
ALTER USER 'o9deposit'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9deposit`;
GRANT ALL PRIVILEGES ON `o9deposit`.* TO 'o9deposit'@'%';
GRANT ALL PRIVILEGES ON `o9deposit\_%`.* TO 'o9deposit'@'%';

CREATE USER 'o9fac'@'%' IDENTIFIED BY 'o9fac';
GRANT ALL PRIVILEGES ON *.* TO 'o9fac'@'%' WITH GRANT OPTION;
ALTER USER 'o9fac'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9fac`;
GRANT ALL PRIVILEGES ON `o9fac`.* TO 'o9fac'@'%';
GRANT ALL PRIVILEGES ON `o9fac\_%`.* TO 'o9fac'@'%';

CREATE USER 'o9mortgage'@'%' IDENTIFIED BY 'o9mortgage';
GRANT ALL PRIVILEGES ON *.* TO 'o9mortgage'@'%' WITH GRANT OPTION;
ALTER USER 'o9mortgage'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9mortgage`;
GRANT ALL PRIVILEGES ON `o9mortgage`.* TO 'o9mortgage'@'%';
GRANT ALL PRIVILEGES ON `o9mortgage\_%`.* TO 'o9mortgage'@'%';

CREATE USER 'o9payment'@'%' IDENTIFIED BY 'o9payment';
GRANT ALL PRIVILEGES ON *.* TO 'o9payment'@'%' WITH GRANT OPTION;
ALTER USER 'o9payment'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9payment`;
GRANT ALL PRIVILEGES ON `o9payment`.* TO 'o9payment'@'%';
GRANT ALL PRIVILEGES ON `o9payment\_%`.* TO 'o9payment'@'%';

CREATE USER 'o9batch'@'%' IDENTIFIED BY 'o9batch';
GRANT ALL PRIVILEGES ON *.* TO 'o9batch'@'%' WITH GRANT OPTION;
ALTER USER 'o9batch'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9batch`;
GRANT ALL PRIVILEGES ON `o9batch`.* TO 'o9batch'@'%';
GRANT ALL PRIVILEGES ON `o9batch\_%`.* TO 'o9batch'@'%';

CREATE USER 'o9voucher'@'%' IDENTIFIED BY 'o9voucher';
GRANT ALL PRIVILEGES ON *.* TO 'o9voucher'@'%' WITH GRANT OPTION;
ALTER USER 'o9voucher'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9voucher`;
GRANT ALL PRIVILEGES ON `o9voucher`.* TO 'o9voucher'@'%';
GRANT ALL PRIVILEGES ON `o9voucher\_%`.* TO 'o9voucher'@'%';

CREATE USER 'o9design'@'%' IDENTIFIED BY 'o9design';
GRANT ALL PRIVILEGES ON *.* TO 'o9design'@'%' WITH GRANT OPTION;
ALTER USER 'o9design'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9design`;
GRANT ALL PRIVILEGES ON `o9design`.* TO 'o9design'@'%';
GRANT ALL PRIVILEGES ON `o9design\_%`.* TO 'o9design'@'%';

CREATE USER 'o9cms'@'%' IDENTIFIED BY 'o9cms';
GRANT ALL PRIVILEGES ON *.* TO 'o9cms'@'%' WITH GRANT OPTION;
ALTER USER 'o9cms'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9cms`;
GRANT ALL PRIVILEGES ON `o9cms`.* TO 'o9cms'@'%';
GRANT ALL PRIVILEGES ON `o9cms\_%`.* TO 'o9cms'@'%';

CREATE USER 'o9email'@'%' IDENTIFIED BY 'o9email';
GRANT ALL PRIVILEGES ON *.* TO 'o9cms'@'%' WITH GRANT OPTION;
ALTER USER 'o9email'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9email`;
GRANT ALL PRIVILEGES ON `o9email`.* TO 'o9email'@'%';
GRANT ALL PRIVILEGES ON `o9email\_%`.* TO 'o9email'@'%';

CREATE USER 'o9report'@'%' IDENTIFIED BY 'o9report';
GRANT ALL PRIVILEGES ON *.* TO 'o9report'@'%' WITH GRANT OPTION;
ALTER USER 'o9report'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9report`;
GRANT ALL PRIVILEGES ON `o9report`.* TO 'o9report'@'%';
GRANT ALL PRIVILEGES ON `o9report\_%`.* TO 'o9report'@'%';

CREATE USER 'o9ems'@'%' IDENTIFIED BY 'o9ems';
GRANT ALL PRIVILEGES ON *.* TO 'o9ems'@'%' WITH GRANT OPTION;
ALTER USER 'o9ems'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9ems`;
GRANT ALL PRIVILEGES ON `o9ems`.* TO 'o9ems'@'%';
GRANT ALL PRIVILEGES ON `o9ems\_%`.* TO 'o9ems'@'%';

CREATE USER 'o9sample'@'%' IDENTIFIED BY 'o9sample';
GRANT ALL PRIVILEGES ON *.* TO 'o9sample'@'%' WITH GRANT OPTION;
ALTER USER 'o9sample'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9sample`;
GRANT ALL PRIVILEGES ON `o9sample`.* TO 'o9sample'@'%';
GRANT ALL PRIVILEGES ON `o9sample\_%`.* TO 'o9sample'@'%';

CREATE USER 'o9acw'@'%' IDENTIFIED BY 'o9acw';
GRANT ALL PRIVILEGES ON *.* TO 'o9acw'@'%' WITH GRANT OPTION;
ALTER USER 'o9acw'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9acw`;
GRANT ALL PRIVILEGES ON `o9acw`.* TO 'o9acw'@'%';
GRANT ALL PRIVILEGES ON `o9acw\_%`.* TO 'o9acw'@'%';

CREATE USER 'o9wal'@'%' IDENTIFIED BY 'o9wal';
GRANT ALL PRIVILEGES ON *.* TO 'o9wal'@'%' WITH GRANT OPTION;
ALTER USER 'o9wal'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9wal`;
GRANT ALL PRIVILEGES ON `o9wal`.* TO 'o9wal'@'%';
GRANT ALL PRIVILEGES ON `o9wal\_%`.* TO 'o9wal'@'%';

CREATE USER 'o9import'@'%' IDENTIFIED BY 'o9import';
GRANT ALL PRIVILEGES ON *.* TO 'o9import'@'%' WITH GRANT OPTION;
ALTER USER 'o9import'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9import`;
GRANT ALL PRIVILEGES ON `o9import`.* TO 'o9import'@'%';
GRANT ALL PRIVILEGES ON `o9import\_%`.* TO 'o9import'@'%';

CREATE USER 'o9otp'@'%' IDENTIFIED BY 'o9otp';
GRANT ALL PRIVILEGES ON *.* TO 'o9otp'@'%' WITH GRANT OPTION;
ALTER USER 'o9otp'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `o9otp`;
GRANT ALL PRIVILEGES ON `o9otp`.* TO 'o9otp'@'%';
GRANT ALL PRIVILEGES ON `o9otp\_%`.* TO 'o9otp'@'%';