IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

IF SCHEMA_ID(N'NeptuneDB') IS NULL EXEC(N'CREATE SCHEMA [NeptuneDB];');
GO

CREATE TABLE [NeptuneDB].[AUTH_ORGANIZATION] (
    [OrganizationID] nvarchar(100) NOT NULL,
    [OrganizationCode] nvarchar(100) NOT NULL,
    [OrganizationName] nvarchar(500) NOT NULL,
    [Phone] nvarchar(50) NULL,
    [Status] nvarchar(10) NOT NULL,
    [Email] nvarchar(1000) NULL,
    [Website] nvarchar(1000) NULL,
    [welcome_logo] text NULL,
    [login_background] text NULL,
    CONSTRAINT [PK_AUTH_ORGANIZATION] PRIMARY KEY ([OrganizationID])
);
GO

CREATE TABLE [NeptuneDB].[AUTH_ROLE] (
    [RoleID] nvarchar(100) NOT NULL,
    [RoleCode] nvarchar(100) NOT NULL,
    [RoleName] nvarchar(500) NOT NULL,
    CONSTRAINT [PK_AUTH_ROLE] PRIMARY KEY ([RoleID])
);
GO

CREATE TABLE [NeptuneDB].[AUTH_ROLE_USER] (
    [RoleID] nvarchar(100) NOT NULL,
    [UserID] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_AUTH_ROLE_USER] PRIMARY KEY ([RoleID], [UserID])
);
GO

CREATE TABLE [NeptuneDB].[AUTH_ROLE_WF] (
    [RoleID] nvarchar(100) NOT NULL,
    [WorflowID] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_AUTH_ROLE_WF] PRIMARY KEY ([RoleID], [WorflowID])
);
GO

CREATE TABLE [NeptuneDB].[AUTH_USER] (
    [UserID] nvarchar(100) NOT NULL,
    [UserCode] nvarchar(100) NOT NULL,
    [OrganizationID] nvarchar(100) NOT NULL,
    [UserName] nvarchar(500) NULL,
    [FullName] nvarchar(500) NULL,
    [Status] nvarchar(10) NOT NULL,
    [LanguageCode] nvarchar(2) NOT NULL,
    [SessionExpirationInMinutes] int NOT NULL,
    [HashPassword] nvarchar(500) NULL,
    [PastHashPassword1] nvarchar(500) NULL,
    [PastHashPassword2] nvarchar(500) NULL,
    [PastHashPassword3] nvarchar(500) NULL,
    [PastHashPassword4] nvarchar(500) NULL,
    [PastHashPassword5] nvarchar(500) NULL,
    [PastHashPassword6] nvarchar(500) NULL,
    [PastHashPassword7] nvarchar(500) NULL,
    [PastHashPassword8] nvarchar(500) NULL,
    [PastHashPassword9] nvarchar(500) NULL,
    [PastHashPassword10] nvarchar(500) NULL,
    [FailureCount] int NOT NULL,
    [PasswordCreatedDate] bigint NOT NULL,
    [TimeZone] decimal(18,2) NULL,
    CONSTRAINT [PK_AUTH_USER] PRIMARY KEY ([UserID])
);
GO

CREATE TABLE [NeptuneDB].[CONFIGURATION] (
    [PARA_CODE] nvarchar(500) NOT NULL,
    [PARA_VALUE] nvarchar(4000) NULL,
    CONSTRAINT [PK_CONFIGURATION] PRIMARY KEY ([PARA_CODE])
);
GO

CREATE TABLE [NeptuneDB].[ENVIRONMENT_VARIABLE] (
    [VARIABLE_NAME] nvarchar(500) NOT NULL,
    [E1] text NULL,
    [E2] text NULL,
    [E3] text NULL,
    [E4] text NULL,
    [E5] text NULL,
    [E6] text NULL,
    [E7] text NULL,
    [E8] text NULL,
    [E9] text NULL,
    CONSTRAINT [PK_ENVIRONMENT_VARIABLE] PRIMARY KEY ([VARIABLE_NAME])
);
GO

CREATE TABLE [NeptuneDB].[EVENT_DEF] (
    [EVENT_NAME] nvarchar(500) NOT NULL,
    [STATUS] nvarchar(50) NOT NULL,
    [TYPE] nvarchar(50) NOT NULL,
    [DESCRIPTION] nvarchar(500) NULL,
    CONSTRAINT [PK_EVENT_DEF] PRIMARY KEY ([EVENT_NAME])
);
GO

CREATE TABLE [NeptuneDB].[INSTANCE] (
    [INSTANCE_ID] nvarchar(50) NOT NULL,
    [GRPC_URL] nvarchar(500) NOT NULL,
    [UTC_TIME] bigint NOT NULL,
    [UTC_EXP_TIME] bigint NOT NULL,
    [SERVICE_ID] nvarchar(100) NULL,
    [EVENT_QUEUE_NAME] nvarchar(500) NULL,
    [COMMAND_QUEUE_NAME] nvarchar(500) NULL,
    CONSTRAINT [PK_INSTANCE] PRIMARY KEY ([INSTANCE_ID])
);
GO

CREATE TABLE [NeptuneDB].[JWT] (
    [ID] nvarchar(1000) NOT NULL,
    [token] nvarchar(1000) NOT NULL,
    [valid_from] bigint NOT NULL,
    [valid_to] bigint NOT NULL,
    [user_id] nvarchar(1000) NOT NULL,
    [user_code] nvarchar(1000) NOT NULL,
    [user_name] nvarchar(1000) NOT NULL,
    [organization_id] nvarchar(1000) NOT NULL,
    [organization_code] nvarchar(1000) NOT NULL,
    [organization_name] nvarchar(1000) NOT NULL,
    CONSTRAINT [PK_JWT] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [NeptuneDB].[JWT_STATIC] (
    [ID] nvarchar(1000) NOT NULL,
    [token] nvarchar(1000) NOT NULL,
    [valid_from] bigint NOT NULL,
    [valid_to] bigint NOT NULL,
    [user_id] nvarchar(1000) NOT NULL,
    [user_code] nvarchar(1000) NOT NULL,
    [user_name] nvarchar(1000) NOT NULL,
    [organization_id] nvarchar(1000) NOT NULL,
    [organization_code] nvarchar(1000) NOT NULL,
    [organization_name] nvarchar(1000) NOT NULL,
    CONSTRAINT [PK_JWT_STATIC] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [NeptuneDB].[LANGUAGE_RESOURCE] (
    [RESOURCE_CODE] nvarchar(500) NOT NULL,
    [ID] nvarchar(100) NOT NULL,
    [EN] text NOT NULL,
    [VI] text NULL,
    [LA] text NULL,
    [KR] text NULL,
    [MM] text NULL,
    [TH] text NULL,
    CONSTRAINT [PK_LANGUAGE_RESOURCE] PRIMARY KEY ([RESOURCE_CODE])
);
GO

CREATE TABLE [NeptuneDB].[LOG_API] (
    [AUDIT_ID] nvarchar(100) NOT NULL,
    [UTC_TIME] bigint NOT NULL,
    [REQUEST_SCHEME] nvarchar(100) NULL,
    [REQUEST_SERVER_IP] nvarchar(100) NULL,
    [REQUEST_PATH] nvarchar(4000) NULL,
    [REQUEST_HOST] nvarchar(4000) NULL,
    [REQUEST_BODY] text NULL,
    [LOGIN_USER_ID] nvarchar(100) NULL,
    [LOGIN_ORGANIZATION_ID] nvarchar(100) NULL,
    [RESPONSE_EXECUTION_ID] nvarchar(100) NULL,
    [RESPONSE_DESCRIPTION] nvarchar(4000) NULL,
    [RESPONSE_STATUS] nvarchar(100) NULL,
    [RESPONSE_DATA] text NULL,
    [TRACK_CHANGE] text NULL,
    CONSTRAINT [PK_LOG_API] PRIMARY KEY ([AUDIT_ID])
);
GO

CREATE TABLE [NeptuneDB].[LOG_EVENT] (
    [EVENT_ID] nvarchar(50) NOT NULL,
    [INSTANCE_ID] nvarchar(500) NOT NULL,
    [RUNNING_ID] nvarchar(500) NOT NULL,
    [EVENT_TYPE] nvarchar(100) NOT NULL,
    [UTC_TIME] bigint NOT NULL,
    [DESCS] text NOT NULL,
    [EVENT_DATA] text NULL,
    CONSTRAINT [PK_LOG_EVENT] PRIMARY KEY ([EVENT_ID])
);
GO

CREATE TABLE [NeptuneDB].[LOG_GRPC] (
    [ID] nvarchar(50) NOT NULL,
    [INSTANCE_ID] nvarchar(500) NOT NULL,
    [RUNNING_ID] nvarchar(500) NOT NULL,
    [SERVER_TIME] bigint NOT NULL,
    [FROM_SERVICE_ID] nvarchar(100) NULL,
    [TO_SERVICE_ID] nvarchar(100) NULL,
    [METHOD_SPEC] nvarchar(4000) NULL,
    [METHOD_RESULT] text NULL,
    CONSTRAINT [PK_LOG_GRPC] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [NeptuneDB].[LOG_HTTP_REQUEST] (
    [REQUEST_ID] nvarchar(100) NOT NULL,
    [TIME_IN] bigint NOT NULL,
    [TIME_OUT] bigint NOT NULL,
    [DATA] text NULL,
    CONSTRAINT [PK_LOG_HTTP_REQUEST] PRIMARY KEY ([REQUEST_ID])
);
GO

CREATE TABLE [NeptuneDB].[LOG_INCOMING_QUEUE_MESSAGE] (
    [MESSAGE_ID] nvarchar(100) NOT NULL,
    [COMING_TIME] bigint NOT NULL,
    [COMING_STATUS] nvarchar(50) NOT NULL,
    [COMING_CONTENT] text NULL,
    [PROCESSING_ERROR] text NULL,
    [REQUEST_EXEC_STEP_ID] nvarchar(100) NULL,
    [RESPONSE_STATUS] nvarchar(100) NULL,
    [RESPONSE_OUTPUT] text NULL,
    CONSTRAINT [PK_LOG_INCOMING_QUEUE_MESSAGE] PRIMARY KEY ([MESSAGE_ID])
);
GO

CREATE TABLE [NeptuneDB].[LOG_RECEIVING_HTTP] (
    [HTTP_ID] nvarchar(100) NOT NULL,
    [TIME_START] bigint NOT NULL,
    [TIME_FINISH] bigint NOT NULL,
    [RECEIVING_DATA] text NULL,
    [SENDING_DATA] text NULL,
    [ERROR_DATA] text NULL,
    CONSTRAINT [PK_LOG_RECEIVING_HTTP] PRIMARY KEY ([HTTP_ID])
);
GO

CREATE TABLE [NeptuneDB].[SENDING_HTTP] (
    [HTTP_ID] nvarchar(100) NOT NULL,
    [TIME_START] bigint NOT NULL,
    [TIME_FINISH] bigint NOT NULL,
    [SENDING_DATA] text NULL,
    [RECEIVING_DATA] text NULL,
    [ERROR_DATA] text NULL,
    CONSTRAINT [PK_SENDING_HTTP] PRIMARY KEY ([HTTP_ID])
);
GO

CREATE TABLE [NeptuneDB].[SERVICE_DEF] (
    [SERVICE_ID] nvarchar(100) NOT NULL,
    [SERVICE_CODE] nvarchar(100) NOT NULL,
    [SERVICE_NAME] nvarchar(4000) NOT NULL,
    [STATUS] nvarchar(50) NOT NULL,
    [QUEUE_NAME] nvarchar(100) NOT NULL,
    [ACCEPT_TIME] bigint NOT NULL,
    [GRPC_STATUS] nvarchar(50) NOT NULL,
    [GRPC_TIMEOUT] bigint NOT NULL,
    [GRPC_URL] nvarchar(500) NULL,
    [EVENT_REGISTRATION] nvarchar(50) NOT NULL,
    [IMPORT_EXPORT_STEP_CODE] nvarchar(50) NOT NULL,
    [CONCURRENT_THREADS] bigint NOT NULL,
    [SERVICE_INSTANCE_TYPE] nvarchar(50) NOT NULL,
    CONSTRAINT [PK_SERVICE_DEF] PRIMARY KEY ([SERVICE_ID])
);
GO

CREATE TABLE [NeptuneDB].[WF_DEF] (
    [WFID] nvarchar(100) NOT NULL,
    [Code] nvarchar(100) NULL,
    [Name] nvarchar(500) NULL,
    [Status] nvarchar(100) NOT NULL,
    [AllowReversal] nvarchar(100) NOT NULL,
    [Description] nvarchar(500) NULL,
    [TimeoutInMiliseconds] bigint NOT NULL,
    [KeepExecSeconds] bigint NOT NULL,
    [OpenAPITags] nvarchar(500) NULL,
    [OpenAPIResponse] nvarchar(max) NULL,
    [OpenAPIResponseSpec] nvarchar(max) NULL,
    [EventWorkflowRegistered] nvarchar(50) NOT NULL,
    [EventWorkflowCompleted] nvarchar(50) NOT NULL,
    [EventWorkflowError] nvarchar(50) NOT NULL,
    [EventWorkflowTimeout] nvarchar(50) NOT NULL,
    [EventWorkflowCompensated] nvarchar(50) NOT NULL,
    [EventWorkflowReversed] nvarchar(50) NOT NULL,
    [EventWorkflowStepStart] nvarchar(50) NOT NULL,
    [EventWorkflowStepCompleted] nvarchar(50) NOT NULL,
    [EventWorkflowStepError] nvarchar(50) NOT NULL,
    [EventWorkflowStepTimeout] nvarchar(50) NOT NULL,
    [EventWorkflowStepCompensated] nvarchar(50) NOT NULL,
    CONSTRAINT [PK_WF_DEF] PRIMARY KEY ([WFID])
);
GO

CREATE TABLE [NeptuneDB].[WF_EXEC] (
    [EXECUTION_ID] nvarchar(100) NOT NULL,
    [USER_ID] nvarchar(100) NOT NULL,
    [ORGANIZATION_ID] nvarchar(100) NOT NULL,
    [INPUT] text NOT NULL,
    [WFID] nvarchar(100) NOT NULL,
    [LANG] nvarchar(2) NOT NULL,
    [CREATED_ON] bigint NOT NULL,
    [STATUS] nvarchar(100) NOT NULL,
    [FINISH_ON] bigint NOT NULL,
    [IS_SUCCESS] nvarchar(100) NOT NULL,
    [IS_TIMEOUT] nvarchar(100) NOT NULL,
    [IS_PROCESSING] nvarchar(100) NOT NULL,
    [STOP_ERROR] text NULL,
    [WORKFLOW_TYPE] nvarchar(100) NOT NULL,
    [REVERSED_EXECUTION_ID] nvarchar(100) NOT NULL,
    [REVERSED_BY_EXECUTION_ID] nvarchar(100) NOT NULL,
    [IS_DISPUTED] nvarchar(450) NOT NULL,
    [ARCHIVING_TIME] bigint NOT NULL,
    [PURGING_TIME] bigint NOT NULL,
    [TX_CONTEXT] text NOT NULL,
    [APPROVED_EXECUTION_ID] nvarchar(100) NULL,
    [SERVICE_INSTANCES] nvarchar(2000) NULL,
    CONSTRAINT [PK_WF_EXEC] PRIMARY KEY ([EXECUTION_ID])
);
GO

CREATE TABLE [NeptuneDB].[WF_EXEC_DONE] (
    [EXECUTION_ID] nvarchar(100) NOT NULL,
    [USER_ID] nvarchar(100) NOT NULL,
    [ORGANIZATION_ID] nvarchar(100) NOT NULL,
    [INPUT] text NOT NULL,
    [WFID] nvarchar(100) NOT NULL,
    [LANG] nvarchar(2) NOT NULL,
    [CREATED_ON] bigint NOT NULL,
    [STATUS] nvarchar(100) NOT NULL,
    [FINISH_ON] bigint NOT NULL,
    [IS_SUCCESS] nvarchar(100) NOT NULL,
    [IS_TIMEOUT] nvarchar(100) NOT NULL,
    [IS_PROCESSING] nvarchar(100) NOT NULL,
    [STOP_ERROR] text NULL,
    [WORKFLOW_TYPE] nvarchar(100) NOT NULL,
    [REVERSED_EXECUTION_ID] nvarchar(100) NOT NULL,
    [REVERSED_BY_EXECUTION_ID] nvarchar(100) NOT NULL,
    [IS_DISPUTED] nvarchar(450) NOT NULL,
    [ARCHIVING_TIME] bigint NOT NULL,
    [PURGING_TIME] bigint NOT NULL,
    [TX_CONTEXT] text NOT NULL,
    [APPROVED_EXECUTION_ID] nvarchar(100) NULL,
    [SERVICE_INSTANCES] nvarchar(2000) NULL,
    CONSTRAINT [PK_WF_EXEC_DONE] PRIMARY KEY ([EXECUTION_ID])
);
GO

CREATE TABLE [NeptuneDB].[WF_FIELD] (
    [WORKFLOW_ID] nvarchar(100) NOT NULL,
    [FIELD_CODE] nvarchar(100) NOT NULL,
    [FIELD_KEY] nvarchar(100) NOT NULL,
    [DATA_TYPE] nvarchar(100) NOT NULL,
    [IS_NULL] nvarchar(100) NOT NULL,
    [IS_REQUIRED] nvarchar(100) NOT NULL,
    [NUM_MIN] decimal(18,2) NOT NULL,
    [NUM_MAX] decimal(18,2) NOT NULL,
    [NUM_RANGE] text NULL,
    [TEXT_MIN] text NULL,
    [TEXT_MAX] text NULL,
    [TEXT_RANGE] text NULL,
    [TEXT_MAXLENGTH] int NOT NULL,
    [DATE_MIN] decimal(18,2) NOT NULL,
    [DATE_MAX] decimal(18,2) NOT NULL,
    [DATE_RANGE] text NULL,
    [BASE64_ICON] text NULL,
    [OPENAPI_EXAMPLE] nvarchar(max) NULL,
    [OPENAPI_DESCRIPTION] nvarchar(max) NULL,
    CONSTRAINT [PK_WF_FIELD] PRIMARY KEY ([WORKFLOW_ID], [FIELD_CODE])
);
GO

CREATE TABLE [NeptuneDB].[WF_GROUP_EXEC] (
    [EXECUTION_ID] nvarchar(100) NOT NULL,
    [STEP_GROUP] int NOT NULL,
    [P1_STATUS] nvarchar(100) NOT NULL,
    [P2_STATUS] nvarchar(100) NOT NULL,
    [P1_START] bigint NOT NULL,
    [P1_FINISH] bigint NOT NULL,
    [P1_ERROR] text NULL,
    CONSTRAINT [PK_WF_GROUP_EXEC] PRIMARY KEY ([EXECUTION_ID], [STEP_GROUP])
);
GO

CREATE TABLE [NeptuneDB].[WF_GROUP_EXEC_DONE] (
    [EXECUTION_ID] nvarchar(100) NOT NULL,
    [STEP_GROUP] int NOT NULL,
    [P1_STATUS] nvarchar(100) NOT NULL,
    [P2_STATUS] nvarchar(100) NOT NULL,
    [P1_START] bigint NOT NULL,
    [P1_FINISH] bigint NOT NULL,
    [P1_ERROR] text NULL,
    CONSTRAINT [PK_WF_GROUP_EXEC_DONE] PRIMARY KEY ([EXECUTION_ID], [STEP_GROUP])
);
GO

CREATE TABLE [NeptuneDB].[WF_STEP_DEF] (
    [WFID] nvarchar(100) NOT NULL,
    [STEP_ORDER] int NOT NULL,
    [STEP_GROUP] int NOT NULL,
    [STEP_CODE] nvarchar(100) NULL,
    [STATUS] nvarchar(100) NOT NULL,
    [DESCRIPTION] nvarchar(4000) NULL,
    [SERVICE_ID] nvarchar(100) NULL,
    [SENDING_TEMPLATE] text NULL,
    [SUCCESS_CONDITION] text NULL,
    [REQUEST_PROTOCOL] nvarchar(1000) NULL,
    [REQUEST_SERVER_IP] nvarchar(100) NULL,
    [REQUEST_SERVER_PORT] nvarchar(100) NULL,
    [REQUEST_URI] nvarchar(100) NULL,
    [SEND_BY_BROKER] nvarchar(100) NOT NULL,
    [STEP_TIMEOUT] nvarchar(100) NULL,
    [STEP_MODE] nvarchar(20) NOT NULL,
    [BASE64_ICON] text NULL,
    [SENDING_CONDITION] text NULL,
    [ON_COMPENSATING] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_WF_STEP_DEF] PRIMARY KEY ([WFID], [STEP_ORDER])
);
GO

CREATE TABLE [NeptuneDB].[WF_STEP_EXEC] (
    [STEP_EXECUTION_ID] nvarchar(100) NOT NULL,
    [EXECUTION_ID] nvarchar(100) NOT NULL,
    [WORKFLOW_ID] nvarchar(100) NULL,
    [STEP_GROUP] int NOT NULL,
    [STEP_ORDER] int NOT NULL,
    [STEP_CODE] nvarchar(100) NULL,
    [P1_REQUEST_ID] nvarchar(100) NULL,
    [P1_START] bigint NOT NULL,
    [P1_FINISH] bigint NOT NULL,
    [P1_STATUS] nvarchar(100) NOT NULL,
    [P1_ERROR] text NOT NULL,
    [P1_CONTENT] text NOT NULL,
    [P2_REQUEST_ID] nvarchar(100) NULL,
    [P2_START] bigint NOT NULL,
    [P2_FINISH] bigint NOT NULL,
    [P2_STATUS] nvarchar(100) NOT NULL,
    [P2_RESPONSE_STATUS] nvarchar(100) NULL,
    [P2_ERROR] text NULL,
    [P2_CONTENT] text NULL,
    [IS_SUCCESS] nvarchar(100) NOT NULL,
    [IS_TIMEOUT] nvarchar(100) NOT NULL,
    [P3_START] bigint NOT NULL,
    [P3_FINISH] bigint NOT NULL,
    [P3_STATUS] nvarchar(100) NOT NULL,
    [P3_CONTENT] text NULL,
    [P3_ERROR] text NULL,
    [SENDING_CONDITION] text NULL,
    [P4_STATUS] nvarchar(max) NOT NULL,
    [IS_DISPUTED] nvarchar(450) NOT NULL,
    [P4_CONTENT] text NULL,
    CONSTRAINT [PK_WF_STEP_EXEC] PRIMARY KEY ([STEP_EXECUTION_ID])
);
GO

CREATE TABLE [NeptuneDB].[WF_STEP_EXEC_DONE] (
    [STEP_EXECUTION_ID] nvarchar(100) NOT NULL,
    [EXECUTION_ID] nvarchar(100) NOT NULL,
    [WORKFLOW_ID] nvarchar(100) NULL,
    [STEP_GROUP] int NOT NULL,
    [STEP_ORDER] int NOT NULL,
    [STEP_CODE] nvarchar(100) NULL,
    [P1_REQUEST_ID] nvarchar(100) NULL,
    [P1_START] bigint NOT NULL,
    [P1_FINISH] bigint NOT NULL,
    [P1_STATUS] nvarchar(100) NOT NULL,
    [P1_ERROR] text NOT NULL,
    [P1_CONTENT] text NOT NULL,
    [P2_REQUEST_ID] nvarchar(100) NULL,
    [P2_START] bigint NOT NULL,
    [P2_FINISH] bigint NOT NULL,
    [P2_STATUS] nvarchar(100) NOT NULL,
    [P2_RESPONSE_STATUS] nvarchar(100) NULL,
    [P2_ERROR] text NULL,
    [P2_CONTENT] text NULL,
    [IS_SUCCESS] nvarchar(100) NOT NULL,
    [IS_TIMEOUT] nvarchar(100) NOT NULL,
    [P3_START] bigint NOT NULL,
    [P3_FINISH] bigint NOT NULL,
    [P3_STATUS] nvarchar(100) NOT NULL,
    [P3_CONTENT] text NULL,
    [P3_ERROR] text NULL,
    [SENDING_CONDITION] text NULL,
    [P4_STATUS] nvarchar(max) NOT NULL,
    [IS_DISPUTED] nvarchar(450) NOT NULL,
    [P4_CONTENT] text NULL,
    CONSTRAINT [PK_WF_STEP_EXEC_DONE] PRIMARY KEY ([STEP_EXECUTION_ID])
);
GO

CREATE UNIQUE INDEX [IX_AUTH_ORGANIZATION_OrganizationCode] ON [NeptuneDB].[AUTH_ORGANIZATION] ([OrganizationCode]);
GO

CREATE UNIQUE INDEX [IX_AUTH_ROLE_RoleCode] ON [NeptuneDB].[AUTH_ROLE] ([RoleCode]);
GO

CREATE UNIQUE INDEX [IX_AUTH_USER_UserCode] ON [NeptuneDB].[AUTH_USER] ([UserCode]);
GO

CREATE INDEX [IX_INSTANCE_SERVICE_ID] ON [NeptuneDB].[INSTANCE] ([SERVICE_ID]);
GO

CREATE INDEX [IX_JWT_token] ON [NeptuneDB].[JWT] ([token]);
GO

CREATE UNIQUE INDEX [IX_LANGUAGE_RESOURCE_RESOURCE_CODE] ON [NeptuneDB].[LANGUAGE_RESOURCE] ([RESOURCE_CODE]);
GO

CREATE INDEX [IX_LOG_API_LOGIN_ORGANIZATION_ID] ON [NeptuneDB].[LOG_API] ([LOGIN_ORGANIZATION_ID]);
GO

CREATE INDEX [IX_LOG_API_LOGIN_USER_ID] ON [NeptuneDB].[LOG_API] ([LOGIN_USER_ID]);
GO

CREATE INDEX [IX_LOG_API_RESPONSE_STATUS] ON [NeptuneDB].[LOG_API] ([RESPONSE_STATUS]);
GO

CREATE INDEX [IX_LOG_API_UTC_TIME] ON [NeptuneDB].[LOG_API] ([UTC_TIME]);
GO

CREATE INDEX [IX_LOG_EVENT_UTC_TIME] ON [NeptuneDB].[LOG_EVENT] ([UTC_TIME]);
GO

CREATE INDEX [IX_LOG_GRPC_INSTANCE_ID] ON [NeptuneDB].[LOG_GRPC] ([INSTANCE_ID]);
GO

CREATE INDEX [IX_LOG_GRPC_RUNNING_ID] ON [NeptuneDB].[LOG_GRPC] ([RUNNING_ID]);
GO

CREATE INDEX [IX_LOG_GRPC_SERVER_TIME] ON [NeptuneDB].[LOG_GRPC] ([SERVER_TIME]);
GO

CREATE UNIQUE INDEX [IX_SERVICE_DEF_SERVICE_CODE] ON [NeptuneDB].[SERVICE_DEF] ([SERVICE_CODE]);
GO

CREATE UNIQUE INDEX [IX_WF_DEF_Code] ON [NeptuneDB].[WF_DEF] ([Code]) WHERE [Code] IS NOT NULL;
GO

CREATE INDEX [IX_WF_EXEC_ARCHIVING_TIME] ON [NeptuneDB].[WF_EXEC] ([ARCHIVING_TIME]);
GO

CREATE INDEX [IX_WF_EXEC_CREATED_ON] ON [NeptuneDB].[WF_EXEC] ([CREATED_ON]);
GO

CREATE INDEX [IX_WF_EXEC_FINISH_ON] ON [NeptuneDB].[WF_EXEC] ([FINISH_ON]);
GO

CREATE INDEX [IX_WF_EXEC_IS_DISPUTED] ON [NeptuneDB].[WF_EXEC] ([IS_DISPUTED]);
GO

CREATE INDEX [IX_WF_EXEC_IS_SUCCESS] ON [NeptuneDB].[WF_EXEC] ([IS_SUCCESS]);
GO

CREATE INDEX [IX_WF_EXEC_IS_TIMEOUT] ON [NeptuneDB].[WF_EXEC] ([IS_TIMEOUT]);
GO

CREATE INDEX [IX_WF_EXEC_ORGANIZATION_ID] ON [NeptuneDB].[WF_EXEC] ([ORGANIZATION_ID]);
GO

CREATE INDEX [IX_WF_EXEC_PURGING_TIME] ON [NeptuneDB].[WF_EXEC] ([PURGING_TIME]);
GO

CREATE INDEX [IX_WF_EXEC_STATUS] ON [NeptuneDB].[WF_EXEC] ([STATUS]);
GO

CREATE INDEX [IX_WF_EXEC_USER_ID] ON [NeptuneDB].[WF_EXEC] ([USER_ID]);
GO

CREATE INDEX [IX_WF_EXEC_WFID] ON [NeptuneDB].[WF_EXEC] ([WFID]);
GO

CREATE INDEX [IX_WF_EXEC_WORKFLOW_TYPE] ON [NeptuneDB].[WF_EXEC] ([WORKFLOW_TYPE]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_ARCHIVING_TIME] ON [NeptuneDB].[WF_EXEC_DONE] ([ARCHIVING_TIME]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_CREATED_ON] ON [NeptuneDB].[WF_EXEC_DONE] ([CREATED_ON]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_FINISH_ON] ON [NeptuneDB].[WF_EXEC_DONE] ([FINISH_ON]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_IS_DISPUTED] ON [NeptuneDB].[WF_EXEC_DONE] ([IS_DISPUTED]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_IS_SUCCESS] ON [NeptuneDB].[WF_EXEC_DONE] ([IS_SUCCESS]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_IS_TIMEOUT] ON [NeptuneDB].[WF_EXEC_DONE] ([IS_TIMEOUT]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_ORGANIZATION_ID] ON [NeptuneDB].[WF_EXEC_DONE] ([ORGANIZATION_ID]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_PURGING_TIME] ON [NeptuneDB].[WF_EXEC_DONE] ([PURGING_TIME]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_STATUS] ON [NeptuneDB].[WF_EXEC_DONE] ([STATUS]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_USER_ID] ON [NeptuneDB].[WF_EXEC_DONE] ([USER_ID]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_WFID] ON [NeptuneDB].[WF_EXEC_DONE] ([WFID]);
GO

CREATE INDEX [IX_WF_EXEC_DONE_WORKFLOW_TYPE] ON [NeptuneDB].[WF_EXEC_DONE] ([WORKFLOW_TYPE]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_EXECUTION_ID] ON [NeptuneDB].[WF_STEP_EXEC] ([EXECUTION_ID]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_IS_DISPUTED] ON [NeptuneDB].[WF_STEP_EXEC] ([IS_DISPUTED]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_IS_SUCCESS] ON [NeptuneDB].[WF_STEP_EXEC] ([IS_SUCCESS]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_IS_TIMEOUT] ON [NeptuneDB].[WF_STEP_EXEC] ([IS_TIMEOUT]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P1_FINISH] ON [NeptuneDB].[WF_STEP_EXEC] ([P1_FINISH]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P1_START] ON [NeptuneDB].[WF_STEP_EXEC] ([P1_START]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P1_STATUS] ON [NeptuneDB].[WF_STEP_EXEC] ([P1_STATUS]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P2_FINISH] ON [NeptuneDB].[WF_STEP_EXEC] ([P2_FINISH]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P2_START] ON [NeptuneDB].[WF_STEP_EXEC] ([P2_START]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P2_STATUS] ON [NeptuneDB].[WF_STEP_EXEC] ([P2_STATUS]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P3_FINISH] ON [NeptuneDB].[WF_STEP_EXEC] ([P3_FINISH]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P3_START] ON [NeptuneDB].[WF_STEP_EXEC] ([P3_START]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_P3_STATUS] ON [NeptuneDB].[WF_STEP_EXEC] ([P3_STATUS]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_STEP_CODE] ON [NeptuneDB].[WF_STEP_EXEC] ([STEP_CODE]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_WORKFLOW_ID] ON [NeptuneDB].[WF_STEP_EXEC] ([WORKFLOW_ID]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_EXECUTION_ID] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([EXECUTION_ID]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_IS_DISPUTED] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([IS_DISPUTED]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_IS_SUCCESS] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([IS_SUCCESS]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_IS_TIMEOUT] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([IS_TIMEOUT]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P1_FINISH] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P1_FINISH]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P1_START] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P1_START]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P1_STATUS] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P1_STATUS]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P2_FINISH] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P2_FINISH]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P2_START] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P2_START]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P2_STATUS] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P2_STATUS]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P3_FINISH] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P3_FINISH]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P3_START] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P3_START]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_P3_STATUS] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([P3_STATUS]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_STEP_CODE] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([STEP_CODE]);
GO

CREATE INDEX [IX_WF_STEP_EXEC_DONE_WORKFLOW_ID] ON [NeptuneDB].[WF_STEP_EXEC_DONE] ([WORKFLOW_ID]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20221024014636_v1', N'6.0.10');
GO

COMMIT;
GO

