FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base
WORKDIR /app
EXPOSE 100
EXPOSE 105
EXPOSE 109

FROM base AS final
WORKDIR /app

RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

COPY ["neptuneserver/publish", "."]
COPY ["neptuneserver/NT.pfx", "."]

ENTRYPOINT ["dotnet", "JITS.Neptune.dll"]